name: Python linter

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
    branches:
      - '**.py'
  pull_request:
    branches:
      - main
      - master


jobs:
  lint:
    runs-on: ubuntu-latest
      
    steps:
     - uses: actions/checkout@v4
     - name: Python Linter
       uses: sunnysid3up/python-linter@master
       with:
         source: "klayout_dot_config"
         strict: "low"
